[package]
name = "gnostr"
version = "0.0.54"
edition = "2021"
description = "gnostr:a git+nostr workflow utility"
authors = ["gnostr <admin@gnostr.org>", "0xtr <oxtrr@protonmail.com>"]
readme = "README.md"
homepage = "https://github.com/gnostr-org/gnostr"
repository = "https://github.com/gnostr-org/gnostr"
license = "MIT"
keywords = ["gnostr", "tool", "nostr"]
categories = ["command-line-utilities"]
build = "build.rs"

[lib]
name = "gnostr"
path = "src/lib/mod.rs"

[features]
default = ["ghemoji", "regex-fancy", "trace-libgit", "vendor-openssl"]
expensive_tests = [] #nostr
ghemoji = ["gh-emoji"]
# regex-* features are mutually exclusive.
regex-fancy = ["syntect/regex-fancy", "two-face/syntect-fancy"]
regex-onig = ["syntect/regex-onig", "two-face/syntect-onig"]
timing = ["scopetime/enabled"]
trace-libgit = ["asyncgit/trace-libgit"]
vendor-openssl = ["asyncgit/vendor-openssl"]

[build-dependencies]
chrono = { version = "0.4", default-features = false, features = ["clock"] }

[dev-dependencies]
##nostr
mockall = "0.11.4"
serial_test = "2.0.0"

env_logger = "0.11"
pretty_assertions = "1.4"
tempfile = "3"

[dependencies]
anyhow = "1.0.75"
async-std = "1.12"
async-trait = "0.1.73"
chacha20poly1305 = "0.10.1"
#clap = { version = "4.3.19", features = ["derive"] }
#console = "0.15.7"
crossterm = { version = "0.28.0", features = ["event-stream", "serde"] }
#clap = { version = "4.5.6", features = ["derive"] }
csv = "1.3.0"
#dialoguer = "0.10.4"
#directories = "5.0.1"
env_logger = "0.11"
#futures = "0.3.28"
futures-core = { version = "0.3", optional = false, default-features = false }
futures-timer = "3.0"
##gnostr-tui provides ngit
##gnostr-tui = { version = "0.0.62", path = "crates/tui" }
#indicatif = "0.17.7"
keyring = "2.0.5"
#log = "0.4"

##cli
nostr_0_32_0 = { package = "nostr", version = "0.32.0" }
nostr-sdk_0_32_0 = { package = "nostr-sdk", version = "0.32.0" }
nostr-sdk_0_37_0 = { package = "nostr-sdk", version = "0.37.0" }

num_cpus = "1.16.0"
once_cell = "1.21.3"
passwords = "3.1.13"
scrypt = "0.11.0"
serde = { version = "1.0.203", features = ["derive"] }
serde_json = "1.0.117"
#serde = { version = "1.0.181", features = ["derive"] }
#serde_json = "1.0.105"
#serde_yaml = "0.9.27"
serial_test = "2.0.0"
sha2 = "0.10.8"
temp-env = "0.3.6"
tokio = { version = "1.33.0", features = ["full"] }
tracing = { version = "0.1.37", features = ["std", "attributes"] }
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
tui-input = "0.11.1"
url = "2.5.0"
ureq = { version = "2", features = ["json", "charset"] }
zeroize = "1.6.0"


##nostr
#async-trait = "0.1.73"
auth-git2 = "0.5.4"
clap = { version = "4.3.19", features = ["derive", "env", "cargo"] }
console = "0.15.7"
dialoguer = "0.10.4"
directories = "5.0.1"
futures = "0.3.28"
git2 = "0.19.0" ## asyncgit ^0.19
indicatif = "0.17.7"

nostr = "0.34.1"
nostr-database = "0.34.0"
nostr-sdk = "0.34.0"
nostr-signer = "0.34.0"
nostr-sqlite = "0.34.0"

serde_yaml = "0.9.27"
####
####
####
####
#test_utils = { path = "test_utils" }
####
####
####
urlencoding = "2.1.3"

##gitui
#anyhow = "1.0"
asyncgit = { path = "./asyncgit", version = "0.26", default-features = false }
backtrace = "0.3"
bitflags = "2.6"
bugreport = "0.5"
bwrap = { version = "1.3", features = ["use_std"] }
bytesize = { version = "1.3", default-features = false }
chrono = { version = "0.4", default-features = false, features = ["clock"] }
##clap = { version = "4.5", features = ["env", "cargo"] }
crossbeam-channel = "0.5"
#crossterm = { version = "0.28", features = ["serde"] }
dirs = "5.0"
easy-cast = "0.5"
filetreelist = { path = "./filetreelist", version = "0.5" }
fuzzy-matcher = "0.3"
gh-emoji = { version = "1.0", optional = true }
hostname = "0.3.1"
indexmap = "2"
itertools = "0.13"
libp2p = { version = "0.54.1", features = [
  "tokio",
  "gossipsub",
  "mdns",
  "noise",
  "macros",
  "tcp",
  "yamux",
  "quic",
] }

log = "0.4"
notify = "6.1"
notify-debouncer-mini = "0.4"
#once_cell = "1"
# pin until upgrading this does not introduce a duplicate dependency
parking_lot_core = "=0.9.9"
ratatui = { version = "0.28", default-features = false, features = [
    'crossterm',
    'serde',
] }
rayon-core = "1.12"
ron = "0.8"
scopeguard = "1.2"
scopetime = { path = "./scopetime", version = "0.1" }
#serde = "1.0"
shellexpand = "3.1"
simplelog = { version = "0.12", default-features = false }
struct-patch = "0.4"
syntect = { version = "5.2", default-features = false, features = [
    "parsing",
    "default-syntaxes",
    "default-themes",
    "html",
] }
tui-textarea = "0.6"
two-face = { version = "0.4.0", default-features = false }
unicode-segmentation = "1.12"
unicode-truncate = "1.0"
unicode-width = "0.1"
which = "6.0"

# The profile that 'dist' will build with
[profile.dist]
inherits = "release"
lto = "thin"
