[package]
name = "gnostr"
version = "0.0.49"
edition = "2021"
description = "cli for code collaboration over nostr with nip34 support"
authors = ["DanConwayDev <DanConwayDev@protonmail.com>"]
readme = "README.md"
homepage = "https://gitworkshop.dev/repo/ngit"
repository = "https://codeberg.org/DanConwayDev/ngit-cli"
license = "MIT"
keywords = ["nostr", "git"]
categories = ["command-line-utilities","git"]

[dependencies]
anyhow = "1.0.75"
async-trait = "0.1.73"
chacha20poly1305 = "0.10.1"
clap = { version = "4.3.19", features = ["derive"] }
console = "0.15.7"
#clap = { version = "4.5.6", features = ["derive"] }
csv = "1.3.0"
dialoguer = "0.10.4"
directories = "5.0.1"
env_logger = "0.11"
futures = "0.3.28"
git2 = "0.18.1"
indicatif = "0.17.7"
keyring = "2.0.5"
log = "0.4"
ngit = { version = "1.2.1", path = "crates/ngit" }
nostr = "0.32.0"
nostr-sdk = "0.32.0"
num_cpus = "1.16.0"
passwords = "3.1.13"
reqwest = "0.12.4"
scrypt = "0.11.0"
serde = { version = "1.0.203", features = ["derive"] }
serde_json = "1.0.117"
#serde = { version = "1.0.181", features = ["derive"] }
#serde_json = "1.0.105"
serde_yaml = "0.9.27"
tokio = { version = "1.38.0", features = ["full"] }
url = "2.5.0"
#tokio = "1.33.0"
zeroize = "1.6.0"

[dev-dependencies]
assert_cmd = "2.0.12"
duplicate = "1.0.0"
mockall = "0.11.4"
once_cell = "1.18.0"
rexpect = "0.5.0"
serial_test = "2.0.0"
gnostr_test_utils = { path = "test_utils" }

[workspace]
members = [
    "test_utils",
]
