[package]
name = "gnostr"
version = "0.0.53"
edition = "2021"
description = "gnostr:a git+nostr workflow utility"
authors = ["gnostr <admin@gnostr.org>", "0xtr <oxtrr@protonmail.com>"]
readme = "README.md"
homepage = "https://github.com/gnostr-org/gnostr"
repository = "https://github.com/gnostr-org/gnostr"
license = "MIT"
keywords = ["gnostr", "tool", "nostr"]
categories = ["command-line-utilities"]

[dependencies]
anyhow = "1.0.75"
async-std = "1.12"
async-trait = "0.1.73"
chacha20poly1305 = "0.10.1"
clap = { version = "4.3.19", features = ["derive"] }
console = "0.15.7"
crossterm = { version = "0.29.0", features = ["event-stream"] }
#clap = { version = "4.5.6", features = ["derive"] }
csv = "1.3.0"
dialoguer = "0.10.4"
directories = "5.0.1"
env_logger = "0.11"
futures = "0.3.28"
futures-core = { version = "0.3", optional = false, default-features = false }
futures-timer = "3.0"
git2 = "0.18.1"
gnostr-ngit = { version = "0.0.1", path = "crates/ngit" }
indicatif = "0.17.7"
keyring = "2.0.5"
log = "0.4"
nostr = "0.32.0"
nostr-sdk = "0.32.0"
#nostr-sdk = "0.32.0"
num_cpus = "1.16.0"
once_cell = "1.21.3"
passwords = "3.1.13"
scrypt = "0.11.0"
serde = { version = "1.0.203", features = ["derive"] }
serde_json = "1.0.117"
#serde = { version = "1.0.181", features = ["derive"] }
#serde_json = "1.0.105"
serde_yaml = "0.9.27"
serial_test = "2.0.0"
sha2 = "0.10.8"
temp-env = "0.3.6"
tokio = { version = "1.38.0", features = ["full"] }
tracing = "0.1"
tracing-subscriber = "0.3"
url = "2.5.0"
zeroize = "1.6.0"

# The profile that 'dist' will build with
[profile.dist]
inherits = "release"
lto = "thin"
