[package]
name = "gnostr"
version = "0.0.58"
authors = ["extrawurst <mail@rusticorn.com>"]
description = "blazing fast terminal-ui for git"
edition = "2021"
rust-version = "1.79"
exclude = [".github/*", ".vscode/*", "assets/*"]
homepage = "https://github.com/extrawurst/gitui"
repository = "https://github.com/extrawurst/gitui"
readme = "README.md"
license = "MIT"
categories = ["command-line-utilities"]
keywords = ["git", "gui", "cli", "terminal", "ui"]
build = "build.rs"
## name = "gnostr-cli"
## version = "1.5.0"
## edition = "2021"
## description = "cli for code collaboration over nostr with nip34 support"
## authors = ["DanConwayDev <DanConwayDev@protonmail.com>"]
## readme = "README.md"
## homepage = "https://gitworkshop.dev/r/naddr1qqzxuemfwsqs6amnwvaz7tmwdaejumr0dspzpgqgmmc409hm4xsdd74sf68a2uyf9pwel4g9mfdg8l5244t6x4jdqvzqqqrhnym0k2qj"
## repository = "https://codeberg.org/DanConwayDev/ngit-cli"
## license = "MIT"
## keywords = ["nostr", "git"]
## categories = ["command-line-utilities","development-tools"]

## deps
[dependencies]
anyhow = "1.0"
asyncgit = { path = "./asyncgit", version = "0.26", default-features = false }
async-trait = "0.1.73"
auth-git2 = "0.5.4"
backtrace = "0.3"
bitflags = "2.6"
bugreport = "0.5"
bwrap = { version = "1.3", features = ["use_std"] }
bytesize = { version = "1.3", default-features = false }
chrono = { version = "0.4", default-features = false, features = ["clock"] }
clap = { version = "4.5", features = ["env", "cargo"] }
console = "0.15.7"
crossbeam-channel = "0.5"
crossterm = { version = "0.28", features = ["serde"] }
dialoguer = "0.10.4"
directories = "5.0.1"
dirs = "5.0"
easy-cast = "0.5"
filetreelist = { path = "./filetreelist", version = "0.5" }
futures = "0.3.28"
fuzzy-matcher = "0.3"
gh-emoji = { version = "1.0", optional = true }
git2 = "0.19.0"
indexmap = "2"
indicatif = "0.17.7"
itertools = "0.13"
log = "0.4"
nostr = "0.34.1"
nostr-database = "0.34.0"
nostr-sdk = "0.34.0"
nostr-signer = "0.34.0"
nostr-sqlite = "0.34.0"
notify = "6.1"
notify-debouncer-mini = "0.4"
once_cell = "1"
# pin until upgrading this does not introduce a duplicate dependency
parking_lot_core = "=0.9.9"
ratatui = { version = "0.28", default-features = false, features = [
    'crossterm',
    'serde',
] }
rayon-core = "1.12"
ron = "0.8"
scopeguard = "1.2"
scopetime = { path = "./scopetime", version = "0.1" }
serde = "1.0"
serde_yaml = "0.9.27"
shellexpand = "3.1"
simplelog = { version = "0.12", default-features = false }
struct-patch = "0.4"
syntect = { version = "5.2", default-features = false, features = [
    "parsing",
    "default-syntaxes",
    "default-themes",
    "html",
] }
tokio = "1.33.0"
tui-textarea = "0.6"
two-face = { version = "0.4.0", default-features = false }
unicode-segmentation = "1.12"
unicode-truncate = "1.0"
unicode-width = "0.1"
urlencoding = "2.1.3"
which = "6.0"
zeroize = "1.6.0"

[dev-dependencies]
assert_cmd = "2.0.12"
duplicate = "1.0.0"
env_logger = "0.11"
mockall = "0.11.4"
once_cell = "1.18.0"
pretty_assertions = "1.4"
serial_test = "2.0.0"
tempfile = "3"
test_utils = { path = "test_utils" }

[build-dependencies]
chrono = { version = "0.4", default-features = false, features = ["clock"] }

[badges]
maintenance = { status = "actively-developed" }

[features]
default = ["ghemoji", "regex-fancy", "trace-libgit", "vendor-openssl"]
ghemoji = ["gh-emoji"]
# regex-* features are mutually exclusive.
regex-fancy = ["syntect/regex-fancy", "two-face/syntect-fancy"]
regex-onig = ["syntect/regex-onig", "two-face/syntect-onig"]
timing = ["scopetime/enabled"]
trace-libgit = ["asyncgit/trace-libgit"]
vendor-openssl = ["asyncgit/vendor-openssl"]
expensive_tests = []

[workspace]
members = [
    "asyncgit",
    "filetreelist",
    "git2-hooks",
    "git2-testing",
    "scopetime",
    "test_utils",
]

# Config for 'cargo dist'
[workspace.metadata.dist]
# The preferred cargo-dist version to use in CI (Cargo.toml SemVer syntax)
cargo-dist-version = "0.21.1"
# CI backends to support
ci = "github"
# The installers to generate for each app
installers = ["shell", "powershell", "homebrew"]
# A GitHub repo to push Homebrew formulas to
tap = "gnostr-org/homebrew-gnostr-org"
# Target platforms to build apps for (Rust target-triple syntax)
targets = ["aarch64-apple-darwin", "x86_64-apple-darwin", "x86_64-unknown-linux-gnu", "x86_64-unknown-linux-musl", "x86_64-pc-windows-msvc"]
# Path that installers should place binaries in
install-path = "CARGO_HOME"
# Publish jobs to run in CI
publish-jobs = ["homebrew"]
# Whether to install an updater program
install-updater = true

[profile.release]
lto = true
opt-level = 'z'     # Optimize for size.
codegen-units = 1
strip = "debuginfo"

# make debug build as fast as release
# usage of utf8 encoding inside tui
# makes their debug profile slow
[profile.dev.package."ratatui"]
opt-level = 3

# The profile that 'cargo dist' will build with
[profile.dist]
inherits = "release"
lto = "thin"

[lib]
name = "ngit"
path = "src/lib/mod.rs"

[[bin]]
name = "gnostr-cli"
path = "src/bin/ngit/main.rs"

[[bin]]
name = "git-remote-nostr"
path = "src/bin/git_remote_nostr/main.rs"
