max_width=70
hard_tabs=true
newline_style="Unix"
unstable_features = true
version = "Two"
imports_granularity = "Crate"
group_imports = "StdExternalCrate"
wrap_comments = true
format_code_in_doc_comments = true
