[package]
name = "gnostr-crawler"
version = "0.0.1"
edition = "2021"
description = "gnostr:a git+nostr workflow utility"
authors = ["gnostr <admin@gnostr.org>", "optout21"]
readme = "README.md"
homepage = "https://github.com/gnostr-org/gnostr"
repository = "https://github.com/gnostr-org/gnostr"
license = "MIT"
keywords = ["gnostr", "tool", "nostr"]
categories = ["command-line-utilities"]

[dependencies]
clap = { version = "4.4.13", features = ["derive"] }
env_logger = "0.10"
git2 = "^0.18"
log = "0.4.24"
nostr-sdk = "0.19.1"
time = "0.1.39"
tokio = "1.26.0"
