[package]
name = "gnostr-app"
version = "0.0.1"
edition = "2021"

[dependencies]
gnostr = { version = "0.0.98", path = ".." }
gpui = { git = "https://github.com/zed-industries/zed" }
unicode-segmentation = "1.12.0"
#smallvec = "1.13.2"
