[package]
name = "gnostr-asyncgit"
version = "0.0.1"
authors = ["gnostr <admin@gnostr.org>", "extrawurst <mail@rusticorn.com>"]
edition = "2021"
description = "allow using git2 in a asynchronous context"
homepage = "https://github.com/extrawurst/gitui"
repository = "https://github.com/extrawurst/gitui"
readme = "README.md"
license = "MIT"
categories = ["concurrency", "asynchronous"]
keywords = ["git"]

[dependencies]
#anyhow = "1.0"
bitflags = "2"
crossbeam-channel = "0.5"
dirs = "5.0"
easy-cast = "0.5"
fuzzy-matcher = "0.3"
git2 = "^0.18"
git2-hooks = { path = "../git2-hooks", version = "0.3" }
log = "0.4"
nostr-sdk = "0.37.0"
# git2 = { path = "../../extern/git2-rs", features = ["vendored-openssl"]}
# git2 = { git="https://github.com/extrawurst/git2-rs.git", rev="fc13dcc", features = ["vendored-openssl"]}
# pinning to vendored openssl, using the git2 feature this gets lost with new resolver
openssl-sys = { version = '0.9', features = ["vendored"], optional = true }
rayon = "1.10"
rayon-core = "1.12"
scopetime = { path = "../scopetime", version = "0.1" }
serde = { version = "1.0.203", features = ["derive"] }
serde_json = "1.0.117"
ssh-key = { version = "0.6.6", features = ["crypto", "encryption"] }
thiserror = "1.0"
unicode-truncate = "1.0"
url = "2.5"

[dev-dependencies]
env_logger = "0.11"
invalidstring = { path = "../invalidstring", version = "0.1" }
pretty_assertions = "1.4"
serial_test = "3.1"
tempfile = "3"

[features]
default = ["trace-libgit"]
trace-libgit = []
vendor-openssl = ["openssl-sys"]
