[package]
name = "gnostr-tui"
version = "0.0.62"
authors = ["gnostr <admin@gnostr.org>", "extrawurst <mail@rusticorn.com>"]
description = "gnostr:a git+nostr workflow utility"
edition = "2021"
rust-version = "1.70"
exclude = [".github/*", ".vscode/*", "assets/*"]
homepage = "https://github.com/gnostr-org/gnostr-tui"
repository = "https://github.com/gnostr-org/gnostr-tui"
readme = "README.md"
license = "MIT"
categories = ["command-line-utilities"]
keywords = ["git", "gui", "cli", "terminal", "ui"]
build = "build.rs"

[[bin]]
name = "gnostr-tui"
path = "src/main.rs"

[lib]
name = "ngit"
path = "src/lib/mod.rs"

[[bin]]
name = "gnostr-cli"
path = "src/bin/ngit.rs"

[[bin]]
name = "git-remote-nostr"
path = "src/bin/git_remote_nostr/main.rs"


[dependencies]

##nostr
async-trait = "0.1.73"
auth-git2 = "0.5.4"
clap = { version = "4.5", features = ["derive", "env", "cargo"] }
console = "0.15.7"
dialoguer = "0.10.4"
directories = "5.0.1"
futures = "0.3.28"
git2 = "^0.19" ## async-gnit ^0.19
indicatif = "0.17.7"
nostr = "0.34.1"
nostr-database = "0.34.0"
nostr-sdk = "0.34.0"
nostr-signer = "0.34.0"
nostr-sqlite = "0.34.0"
serde_yaml = "0.9.27"
test_utils = { package = "gnit_test_utils", path = "test_utils", version = "0.0.1" }
tokio = "1.33.0"
urlencoding = "2.1.3"

##gitui
anyhow = "1.0"
asyncgnit = { path = "asyncgnit", version = "0.0.1", default-features = false }
backtrace = "0.3"
bitflags = "2.6"
bugreport = "0.5"
bwrap = { version = "1.3", features = ["use_std"] }
bytesize = { version = "1.3", default-features = false }
chrono = { version = "0.4", default-features = false, features = ["clock"] }
##clap = { version = "4.5", features = ["env", "cargo"] }
crossbeam-channel = "0.5"
crossterm = { version = "0.28", features = ["serde"] }
dirs = "5.0"
easy-cast = "0.5"
filetreelist = { path = "./filetreelist", version = "0.5" }
fuzzy-matcher = "0.3"
gh-emoji = { version = "1.0", optional = true }
indexmap = "2"
itertools = "0.13"
log = "0.4"
notify = "6.1"
notify-debouncer-mini = "0.4"
once_cell = "1"
# pin until upgrading this does not introduce a duplicate dependency
parking_lot_core = "=0.9.9"
ratatui = { version = "0.28", default-features = false, features = [
    'crossterm',
    'serde',
] }
rayon-core = "1.12"
ron = "0.8"
scopeguard = "1.2"
scopetime = { path = "./scopetime", version = "0.1" }
serde = "1.0"
shellexpand = "3.1"
simplelog = { version = "0.12", default-features = false }
struct-patch = "0.4"
syntect = { version = "5.2", default-features = false, features = [
    "parsing",
    "default-syntaxes",
    "default-themes",
    "html",
] }
tui-textarea = "0.6"
two-face = { version = "0.4.0", default-features = false }
unicode-segmentation = "1.12"
unicode-truncate = "1.0"
unicode-width = "0.1"
which = "6.0"

[dev-dependencies]
##nostr
mockall = "0.11.4"
serial_test = "2.0.0"

env_logger = "0.11"
pretty_assertions = "1.4"
tempfile = "3"

[build-dependencies]
chrono = { version = "0.4", default-features = false, features = ["clock"] }

[badges]
maintenance = { status = "actively-developed" }

[features]
default = ["ghemoji", "regex-fancy", "trace-libgit", "vendor-openssl"]
expensive_tests = [] #nostr
ghemoji = ["gh-emoji"]
# regex-* features are mutually exclusive.
regex-fancy = ["syntect/regex-fancy", "two-face/syntect-fancy"]
regex-onig = ["syntect/regex-onig", "two-face/syntect-onig"]
timing = ["scopetime/enabled"]
trace-libgit = ["asyncgnit/trace-libgit"]
vendor-openssl = ["asyncgnit/vendor-openssl"]

[workspace]
members = [
    "asyncgnit",
    "filetreelist",
    "git2-hooks",
    "git2-testing",
    "scopetime",
    "test_utils"
]

# Config for 'cargo dist'
[workspace.metadata.dist]
# The preferred cargo-dist version to use in CI (Cargo.toml SemVer syntax)
cargo-dist-version = "0.21.1"
# CI backends to support
ci = "github"
# The installers to generate for each app
installers = ["shell", "powershell", "homebrew"]
# A GitHub repo to push Homebrew formulas to
tap = "gnostr-org/homebrew-gnostr-org"
# Target platforms to build apps for (Rust target-triple syntax)
targets = ["aarch64-apple-darwin", "x86_64-apple-darwin", "x86_64-unknown-linux-gnu", "x86_64-unknown-linux-musl"]
# Path that installers should place binaries in
install-path = "CARGO_HOME"
# Publish jobs to run in CI
publish-jobs = ["homebrew"]
# Whether to install an updater program
install-updater = true

[profile.release]
lto = true
opt-level = 'z'     # Optimize for size.
codegen-units = 1
strip = "debuginfo"

# make debug build as fast as release
# usage of utf8 encoding inside tui
# makes their debug profile slow
[profile.dev.package."ratatui"]
opt-level = 3

# The profile that 'cargo dist' will build with
[profile.dist]
inherits = "release"
lto = "thin"
